baseurl = "https://bartelloni.it"
title = "Guglielmo Bartelloni"
theme = "hugo-theme-cleanwhite"
languageCode = "it-it"
# Enable comments by entering your Disqus shortname
disqusShortname = ""
googleAnalytics = ""
preserveTaxonomyNames = true
paginate = 5 #frontpage pagination
hasCJKLanguage = true

[outputs]
home = ["HTML", "RSS"]

[params]
  header_image = "/img/background.jpg"
  SEOTitle = "Home | Blog di Guglilemo Bartelloni"
  description = "Blog personale di Guglielmo Bartelloni"
  keyword = "guglielmo, bartelloni, Guglielmo Bartelloni, linux, bash, arch, chrome os, pixelbook, thinkpad, x230"
  slogan = "Il tempo è cibo per la mente"

  image_404 = "img/404-bg.jpg"
  title_404 = "Pagina non trovata ☹️"
  omit_categories = false

  # leancloud storage for page view counter
  page_view_conter = false 
  leancloud_app_id = ""
  leancloud_app_key = ""

  # algolia site search
  algolia_search = false
  algolia_appId = ""
  algolia_indexName = ""
  algolia_apiKey = ""

  # Sidebar settings
  sidebar_about_description = "Programmatore, Musicista e amante delle cose meravigliose"

  featured_tags = false 
  featured_condition_size = 1 
  
  reward = false 

  friends = false
  bookmarks = false
  about_me = true

  [params.social]
  rss            = true 
  email          = "bartelloni.guglielmo@gmail.com"
  #facebook      = "full profile url in facebook"
  #googleplus    = "full profile url in googleplus"
  #twitter       = "full profile url in twitter"
  #instagram     = "full profile url in instagram"
  github         = "https://github.com/morphingSamurai"
#  medium         = "full profile url in medium"
  #pinterest     = "full profile url in pinterest"
  #reddit        = "full profile url in reddit"
  #gitlab        = "full profile url in gitlab"
  #mastodon      = "full profile url in mastodon"
  #keybase       = "full profile url in keybase"
  #xing          = "https://www.xing.com/profile/yourxingid"
  #git           = "full profile url for git user"
  
  [markup]
  [markup.tableOfContents]
    endLevel = 2
    startLevel = 1
  [markup.highlight]
    style = "dracula"
